"""Update new university fields

Revision ID: 071ad9b57faa
Revises: 5378a4d76dbf
Create Date: 2023-08-13 18:18:22.517284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '071ad9b57faa'
down_revision = '5378a4d76dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_support', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('cost_disclaimer', sa.String(length=128), nullable=True))
        batch_op.drop_column('finacial_support')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finacial_support', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('cost_disclaimer')
        batch_op.drop_column('cost')
        batch_op.drop_column('contact')
        batch_op.drop_column('financial_support')

    # ### end Alembic commands ###
