"""empty message

Revision ID: 22093c70b69b
Revises: 8b01a4197277
Create Date: 2023-07-25 20:35:40.050426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22093c70b69b'
down_revision = '8b01a4197277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uw_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('terms', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_equivalency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uwcourse_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('year_taken', sa.String(length=4), nullable=True),
    sa.Column('student_program', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.ForeignKeyConstraint(['uwcourse_id'], ['uw_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('program')

    op.drop_table('course_equivalency')
    op.drop_table('uw_course')
    op.drop_table('user')
    # ### end Alembic commands ###
