"""Add CourseEquivalency Model

Revision ID: 38740191a554
Revises: b9e4b1660aa8
Create Date: 2023-07-15 18:25:09.505636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38740191a554'
down_revision = 'b9e4b1660aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_equivalency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uwcourse_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('year_taken', sa.String(length=4), nullable=True),
    sa.Column('student_program', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.ForeignKeyConstraint(['uwcourse_id'], ['uw_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_equivalency')
    # ### end Alembic commands ###
