"""increase university field lengths

Revision ID: 673323a4f63d
Revises: 5cb806a3a192
Create Date: 2023-08-14 15:06:40.839574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '673323a4f63d'
down_revision = '5cb806a3a192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('tuition',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('transcript',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('housing',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('financial_support',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('course_info',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('other_info',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('wellness',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.alter_column('wellness',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('other_info',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('course_info',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('financial_support',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('housing',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('transcript',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('tuition',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('requirements',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
