"""Add program and location columns.

Revision ID: 934fce43264f
Revises: 
Create Date: 2023-07-11 12:49:20.563658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934fce43264f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('program')

    # ### end Alembic commands ###
