"""Update university field lengths

Revision ID: a15dca08b79e
Revises: 071ad9b57faa
Create Date: 2023-08-13 19:29:39.922126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a15dca08b79e'
down_revision = '071ad9b57faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_info', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('other_info', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('wellness', sa.String(length=512), nullable=True))
        batch_op.alter_column('transcript',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('housing',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('dates',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('financial_support',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.alter_column('financial_support',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('dates',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('housing',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('transcript',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('wellness')
        batch_op.drop_column('other_info')
        batch_op.drop_column('course_info')

    # ### end Alembic commands ###
