"""Add discussion_post

Revision ID: a940e7351f97
Revises: 8b01a4197277
Create Date: 2023-07-26 16:55:15.765622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a940e7351f97'
down_revision = '8b01a4197277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=128), nullable=True),
    sa.Column('student_faculty', sa.String(length=128), nullable=True),
    sa.Column('student_term', sa.String(length=128), nullable=True),
    sa.Column('housing', sa.String(length=128), nullable=True),
    sa.Column('favourite_aspect', sa.String(length=128), nullable=True),
    sa.Column('food_situation', sa.String(length=128), nullable=True),
    sa.Column('safe_rating', sa.Integer(), nullable=True),
    sa.Column('fun_rating', sa.Integer(), nullable=True),
    sa.Column('affordable_rating', sa.Integer(), nullable=True),
    sa.Column('easy_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussion_post')
    # ### end Alembic commands ###
