"""Initial migration.

Revision ID: db89dd0b1d23
Revises: 
Create Date: 2023-07-15 18:16:22.462214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db89dd0b1d23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('languages', sa.String(length=128), nullable=True),
    sa.Column('terms', sa.String(length=128), nullable=True),
    sa.Column('competition', sa.String(length=128), nullable=True),
    sa.Column('program', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('university')
    # ### end Alembic commands ###
