"""empty message

Revision ID: ef52e75a2aec
Revises: c3a8a01b1af0
Create Date: 2023-08-13 14:10:54.326987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef52e75a2aec'
down_revision = 'c3a8a01b1af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=128), nullable=True),
    sa.Column('student_faculty', sa.String(length=128), nullable=True),
    sa.Column('student_term', sa.String(length=128), nullable=True),
    sa.Column('housing', sa.String(length=128), nullable=True),
    sa.Column('favourite_aspect', sa.String(length=128), nullable=True),
    sa.Column('food_situation', sa.String(length=128), nullable=True),
    sa.Column('safe_rating', sa.Integer(), nullable=True),
    sa.Column('fun_rating', sa.Integer(), nullable=True),
    sa.Column('affordable_rating', sa.Integer(), nullable=True),
    sa.Column('easy_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_equivalency', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('uw_course', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uw_course', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('course_equivalency', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    op.drop_table('discussion_post')
    # ### end Alembic commands ###
